# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BBLHtGDdvHUiK0CtSRDC4bOziE3DEtiA
"""

# KoNLPy 설치 (Google Colab 또는 다른 환경에서)
!pip install konlpy

import konlpy
from konlpy.tag import Okt

# 형태소 분석기 초기화
okt = Okt()

# 분석할 텍스트
text = "오늘은 날씨가 맑아서 기분이 좋다."

# 형태소 분석 및 태깅
morphs = okt.pos(text)

# 명사(Noun), 동사(Verb), 대명사(Proper Noun)만 추출
filtered_words = [word for word, tag in morphs if tag in ['Noun', 'Verb', 'Pronoun']]

print(filtered_words)

